<?php

echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word 1';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word 20';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word';
echo 'hello word 39';
echo 'hello word';
$commencer = false;
if ($commencer) {
    echo 'J\'ai commencé.';
}
